# Generated by Django 4.0.3 on 2022-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
